# Workflow exemple pour AWS
name: CI

on:
  # Permet de lancer la pipeline par action manuelle
  workflow_dispatch:

jobs:
  exemple:
    runs-on: ubuntu-latest
    permissions:
      id-token: write      # Autorise GitHub à générer un token OIDC
      contents: read       # Nécessaire pour checkout

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: arn:aws:iam::069987675187:role/abelhedi
          aws-region: eu-west-1

      - name: List S3 buckets
        shell: bash
        run: |
          # Vérifie l'identité du rôle
          aws sts get-caller-identity

          # Liste les buckets S3
          aws s3 ls
